# Generated by Django 4.0.3 on 2022-04-16 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('rif', models.CharField(max_length=30)),
                ('nombre_clte', models.CharField(max_length=255)),
                ('apellido_clte', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('telefono', models.CharField(max_length=30)),
                ('estatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo_dpto', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre_dpto', models.CharField(max_length=255)),
                ('estatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('numero_fact', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('forma_pago', models.CharField(max_length=255)),
                ('monto_total', models.IntegerField()),
                ('estatus', models.BooleanField(default=True)),
                ('cliente_ced', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaGarantiaApp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('numero_garan', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_venc', models.DateField()),
                ('estatus', models.BooleanField(default=True)),
                ('factura_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaGarantiaApp.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('codigo_mdlo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('descrip_mdlo', models.CharField(max_length=255)),
                ('estatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('codigo_tick', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fecha_creac', models.DateTimeField(auto_now_add=True)),
                ('fecha_act', models.DateTimeField(auto_now_add=True)),
                ('tipo_falla', models.CharField(max_length=255)),
                ('detalle_falla', models.CharField(max_length=255)),
                ('arch_fact', models.FileField(upload_to='')),
                ('cert_garan', models.FileField(upload_to='')),
                ('estatus', models.BooleanField(default=True)),
                ('departamento_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaGarantiaApp.departamento')),
                ('garantia_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaGarantiaApp.garantia')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_prod', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=255)),
                ('nombre_prod', models.CharField(max_length=255)),
                ('descrip_prod', models.CharField(max_length=255)),
                ('existencia', models.IntegerField()),
                ('costo', models.IntegerField()),
                ('meses_garan', models.IntegerField()),
                ('estatus', models.BooleanField(default=True)),
                ('modelo_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaGarantiaApp.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('codigo_detal', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('factura_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaGarantiaApp.factura')),
                ('producto_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaGarantiaApp.producto')),
            ],
        ),
    ]
