# Generated by Django 4.0.3 on 2022-04-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaGarantiaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='codigo_dpto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='codigo_detal',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_fact',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='numero_garan',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='codigo_mdlo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_prod',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='arch_fact',
            field=models.FileField(upload_to='facturas'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cert_garan',
            field=models.FileField(upload_to='garantias'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='codigo_tick',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
